import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiRequestError } from "../lib/api.js";
import { formatDateTime } from "../lib/format.js";
import {
  Button,
  Card,
  EmptyState,
  Field,
  Input,
  Modal,
  Skeleton,
  useToast,
} from "../components/ui.js";
import { cn } from "../lib/utils.js";
import { TICKET_CATEGORIES } from "@aadiinvest/shared";
import type { TicketView } from "@aadiinvest/shared";

const FAQ = [
  {
    q: "Is this real money?",
    a: "No. Market Mayhem is an educational simulation. Every dollar is virtual and no real trades are ever executed.",
  },
  {
    q: "What can I buy?",
    a: "Around 140 simulated listings across five categories: individual stocks, ETFs and funds, crypto, commodities (gold, oil, uranium…) and bonds. Tap any listing in Markets to jump straight into its order ticket.",
  },
  {
    q: "Do I start with a free share?",
    a: "Yes. Every new account gets $800 in the Wallet plus 1 share of Aadidev.co, the house listing, already sitting in the Investment Account.",
  },
  {
    q: "What are the crashes and events?",
    a: "The simulation runs a fixed 50-day timeline with scheduled scenarios: flash crashes, meme frenzies, oil shocks, crypto winters, bailout rallies and more. The Markets and Dashboard tabs show a banner while one is live (with a countdown only for the incoming one, as a rumour).",
  },
  {
    q: "What is the Chaos Lab?",
    a: "A sandbox. It clones your real portfolio, lets you invent scenarios (“Apple +80% on a new phone”), and lets you buy and sell inside that made-up world. The shared simulated market never moves because of your scenario — but if a sandbox sale is profitable, the profit is paid into your real Investment Account (capped at $25,000 per sale). Losses stay in the sandbox.",
  },
  {
    q: "Where do prices come from?",
    a: "All prices are generated by a deterministic simulation that repeats every 50 days — with the scenario crashes and rallies baked into the timeline. Nothing is real market data, and every screen is labeled.",
  },
  {
    q: "How do I start trading?",
    a: "Your $800 sits in your Wallet. Open Wallet → “Transfer to Investment Account”, move some cash over, then buy stocks from Markets or the Trade page.",
  },
  {
    q: "Why can't I buy with my Wallet balance?",
    a: "Wallet money must be transferred to your Investment Account first — just like funding a real brokerage account.",
  },
  {
    q: "How do I earn XP?",
    a: "Complete the tutorial (+100), finish lessons (+25), pass quizzes (+50), place your first trade (+100), unlock achievements, and complete the daily challenge.",
  },
  {
    q: "I sold and my balance looks different than expected — why?",
    a: "Sells settle at the current simulated price, which may differ from your average cost. Your realized profit or loss is shown at sale time.",
  },
];

export default function HelpPage() {
  const [faqQuery, setFaqQuery] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [activeTicket, setActiveTicket] = useState<TicketView | null>(null);
  const [reply, setReply] = useState("");
  const queryClient = useQueryClient();
  const { push } = useToast();

  // Create-ticket form state
  const [subject, setSubject] = useState("");
  const [category, setCategory] = useState<string>(TICKET_CATEGORIES[0]);
  const [description, setDescription] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["tickets"],
    queryFn: () => api.get<{ items: TicketView[] }>("/api/tickets"),
  });

  const filteredFaq = useMemo(
    () =>
      FAQ.filter(
        (f) =>
          f.q.toLowerCase().includes(faqQuery.toLowerCase()) ||
          f.a.toLowerCase().includes(faqQuery.toLowerCase()),
      ),
    [faqQuery],
  );

  const submitTicket = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const res = await api.post<{ ticketNumber: string }>("/api/tickets", {
        subject,
        category,
        description,
      });
      push(`Ticket #${res.ticketNumber} created.`, "success");
      setCreateOpen(false);
      setSubject("");
      setDescription("");
      queryClient.invalidateQueries({ queryKey: ["tickets"] });
    } catch (e) {
      setError(e instanceof ApiRequestError ? e.message : "Could not create ticket.");
    } finally {
      setSubmitting(false);
    }
  };

  const sendReply = async () => {
    if (!activeTicket || !reply.trim()) return;
    await api.post(`/api/tickets/${activeTicket.id}/messages`, { body: reply });
    setReply("");
    const fresh = await api.get<TicketView>(`/api/tickets/${activeTicket.id}`);
    setActiveTicket(fresh);
    queryClient.invalidateQueries({ queryKey: ["tickets"] });
  };

  return (
    <div className="space-y-5 max-w-3xl mx-auto">
      <header className="flex items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Helpdesk</h1>
          <p className="text-sm text-ink-dim mt-0.5">
            Answers, FAQs and support tickets.
          </p>
        </div>
        <Button onClick={() => setCreateOpen(true)}>Create Ticket</Button>
      </header>

      <Card>
        <label className="label">Search help articles</label>
        <Input
          value={faqQuery}
          onChange={(e) => setFaqQuery(e.target.value)}
          placeholder="e.g. transfer, XP, real money…"
        />
        <div className="divide-y divide-edge-soft mt-3">
          {filteredFaq.length === 0 && (
            <p className="text-sm text-ink-dim py-6 text-center">
              No matching articles — create a ticket below and we'll help.
            </p>
          )}
          {filteredFaq.map((f) => (
            <details key={f.q} className="group py-3">
              <summary className="cursor-pointer text-sm font-medium marker:content-none flex items-center justify-between">
                {f.q}
                <span className="text-ink-faint group-open:rotate-180 transition-transform">⌄</span>
              </summary>
              <p className="text-sm text-ink-dim mt-2">{f.a}</p>
            </details>
          ))}
        </div>
      </Card>

      <Card>
        <h2 className="font-semibold mb-3">Your tickets</h2>
        {isLoading ? (
          <Skeleton className="h-24" />
        ) : (data?.items ?? []).length === 0 ? (
          <EmptyState
            icon="💬"
            title="No tickets yet"
            hint="Create a ticket if the FAQ doesn't cover your question."
          />
        ) : (
          <div className="divide-y divide-edge-soft">
            {(data?.items ?? []).map((t) => (
              <button
                key={t.id}
                onClick={() => setActiveTicket(t)}
                className="w-full text-left py-3 flex items-center justify-between gap-3 cursor-pointer"
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium truncate">
                    #{t.ticketNumber} · {t.subject}
                  </p>
                  <p className="text-xs text-ink-faint">
                    {formatDateTime(t.updatedAt)} · {t.messages.length} message
                    {t.messages.length === 1 ? "" : "s"}
                  </p>
                </div>
                <span
                  className={cn(
                    "badge shrink-0",
                    t.status === "OPEN" && "bg-warn/10 text-warn border border-warn/20",
                    t.status === "IN_PROGRESS" && "bg-brand/10 text-brand-strong border border-brand/20",
                    t.status === "RESOLVED" && "bg-up-soft text-up border border-up/20",
                  )}
                >
                  {t.status.replace("_", " ")}
                </span>
              </button>
            ))}
          </div>
        )}
      </Card>

      {/* Create ticket modal */}
      <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Create support ticket">
        <div className="space-y-4">
          <Field label="Subject">
            <Input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="Short summary"
              maxLength={120}
            />
          </Field>
          <Field label="Category">
            <select
              className="input"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
            >
              {TICKET_CATEGORIES.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
          </Field>
          <Field label="Description" error={error ?? undefined}>
            <textarea
              className="input min-h-28"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe the issue (at least 10 characters)"
              maxLength={4000}
            />
          </Field>
          <Button className="w-full" disabled={submitting || subject.length < 3 || description.length < 10} onClick={submitTicket}>
            {submitting ? "Creating…" : "Submit ticket"}
          </Button>
        </div>
      </Modal>

      {/* Ticket thread modal */}
      <Modal
        open={Boolean(activeTicket)}
        onClose={() => setActiveTicket(null)}
        title={activeTicket ? `#${activeTicket.ticketNumber} · ${activeTicket.subject}` : ""}
        wide
      >
        {activeTicket && (
          <div className="space-y-4">
            <div className="space-y-3 max-h-72 overflow-y-auto">
              {activeTicket.messages.map((m) => (
                <div
                  key={m.id}
                  className={cn(
                    "rounded-xl px-4 py-3 text-sm",
                    m.authorRole === "ADMIN" ? "bg-brand/10" : "bg-bg-soft",
                  )}
                >
                  <p className="text-xs font-semibold text-ink-dim mb-1">
                    {m.authorName} · {formatDateTime(m.createdAt)}
                  </p>
                  <p className="whitespace-pre-line">{m.body}</p>
                </div>
              ))}
            </div>
            {activeTicket.status !== "RESOLVED" && (
              <div className="flex gap-2">
                <Input
                  value={reply}
                  onChange={(e) => setReply(e.target.value)}
                  placeholder="Write a reply…"
                />
                <Button onClick={sendReply} disabled={!reply.trim()}>
                  Send
                </Button>
              </div>
            )}
          </div>
        )}
      </Modal>
    </div>
  );
}
