/**
 * Simulated market universe — everything you can buy in the game.
 *
 * EVERY price here is generated by the simulation engine; none of these
 * numbers are real market quotes. `basePrice` values are arbitrary simulation
 * anchors in CAD, documented here for transparency.
 *
 * The catalogue is data-driven: each "section" fixes the exchange, market and
 * asset class, then lists one row per listing. Adding a listing is one line.
 */

export type AssetClass = "STOCK" | "ETF" | "CRYPTO" | "COMMODITY" | "BOND";
export type Market = "US" | "CA" | "AADI";

export interface StockDef {
  symbol: string;
  name: string;
  exchange: string;
  market: Market;
  assetClass: AssetClass;
  sector: string;
  description: string;
  basePrice: number; // simulation anchor price in CAD
  drift: number; // fraction of base added/subtracted across the 50-day cycle
  vol: number; // volatility multiplier applied to the engine's waves
  seed: number; // hash anchor for deterministic per-day wobble
}

/** [symbol, name, sector, basePrice, drift, vol?] */
type Row = [string, string, string, number, number, number?];

interface Section {
  market: Market;
  assetClass: AssetClass;
  exchange: string;
  rows: Row[];
}

/** The house stock: every new player is gifted one share of this listing. */
export const HOUSE_STOCK = "AADIDEV";
export const HOUSE_STOCK_NAME = "Aadidev.co";

const VOL_BY_CLASS: Record<AssetClass, number> = {
  STOCK: 1,
  ETF: 0.7,
  CRYPTO: 3,
  COMMODITY: 2,
  BOND: 0.35,
};

const SECTIONS: Section[] = [
  // ---------------------------------------------------------------- US tech
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NASDAQ (simulated)",
    rows: [
      ["AAPL", "Apple Inc.", "Technology", 192.4, 0.08, 1.1],
      ["MSFT", "Microsoft Corporation", "Technology", 415.75, 0.09],
      ["NVDA", "NVIDIA Corporation", "Semiconductors", 131.2, 0.16, 1.5],
      ["AMD", "Advanced Micro Devices, Inc.", "Semiconductors", 158.4, 0.18, 1.5],
      ["INTC", "Intel Corporation", "Semiconductors", 30.15, 0.14, 1.3],
      ["AVGO", "Broadcom Inc.", "Semiconductors", 168.9, 0.13, 1.2],
      ["QCOM", "Qualcomm Incorporated", "Semiconductors", 172.3, 0.12],
      ["TSM", "Taiwan Semiconductor (ADR)", "Semiconductors", 189.5, 0.12],
      ["ORCL", "Oracle Corporation", "Software", 141.6, 0.11],
      ["CRM", "Salesforce, Inc.", "Software", 268.4, 0.12],
      ["ADBE", "Adobe Inc.", "Software", 512.3, 0.13],
      ["NOW", "ServiceNow, Inc.", "Software", 892.4, 0.12],
      ["SNOW", "Snowflake Inc.", "Software", 128.7, 0.2, 1.6],
      ["PLTR", "Palantir Technologies Inc.", "Software", 68.4, 0.22, 2],
      ["UBER", "Uber Technologies, Inc.", "Software", 74.2, 0.15, 1.2],
      ["MSTR", "MicroStrategy (crypto proxy)", "Software", 178.9, 0.3, 2.6],
      ["SHOP", "Shopify (US listing)", "Software", 96.3, 0.19, 1.7],
      ["INTU", "Intuit Inc.", "Software", 642.8, 0.1],
      ["PANW", "Palo Alto Networks", "Cybersecurity", 318.5, 0.14, 1.4],
      ["CRWD", "CrowdStrike Holdings", "Cybersecurity", 358.2, 0.17, 1.6],
      ["FTNT", "Fortinet, Inc.", "Cybersecurity", 88.6, 0.13, 1.3],
      ["SNPS", "Synopsys Inc.", "Semiconductors", 528.4, 0.12, 1.2],
      ["ARM", "Arm Holdings (ADR)", "Semiconductors", 142.7, 0.2, 1.8],
      ["MU", "Micron Technology", "Semiconductors", 108.9, 0.22, 1.9],
      ["DELL", "Dell Technologies", "Hardware", 124.6, 0.14, 1.3],
      ["HPE", "Hewlett Packard Enterprise", "Hardware", 21.4, 0.12, 1.2],
      ["CSCO", "Cisco Systems, Inc.", "Hardware", 58.7, 0.07, 0.8],
      ["IBM", "International Business Machines", "Software", 224.8, 0.08, 0.9],
      ["SAP", "SAP SE (ADR)", "Software", 218.6, 0.09, 1],
      ["MDB", "MongoDB, Inc.", "Software", 284.5, 0.24, 2.1],
      ["DDOG", "Datadog, Inc.", "Software", 132.8, 0.22, 2],
      ["SHOPX", "Shopverse Holdings", "Software", 42.8, 0.2, 1.9],
      ["AIQ", "Cognivance AI Group", "Software", 67.3, 0.26, 2.2],
    ],
  },
  // ---------------------------------------------------- Communication & media
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NASDAQ (simulated)",
    rows: [
      ["GOOGL", "Alphabet Inc.", "Communication Services", 174.3, 0.1],
      ["META", "Meta Platforms, Inc.", "Communication Services", 512.6, 0.14, 1.3],
      ["NFLX", "Netflix, Inc.", "Communication Services", 685.9, 0.13, 1.3],
      ["DIS", "The Walt Disney Company", "Communication Services", 98.6, 0.11],
      ["SPOT", "Spotify Technology S.A.", "Communication Services", 412.2, 0.16, 1.5],
      ["RBLX", "Roblox Corporation", "Gaming", 46.8, 0.22, 1.8],
      ["EA", "Electronic Arts Inc.", "Gaming", 148.3, 0.1],
      ["TTWO", "Take-Two Interactive", "Gaming", 172.6, 0.14, 1.2],
      ["U", "Unity Software Inc.", "Gaming", 28.4, 0.26, 2.2],
      ["MTCH", "Match Group, Inc.", "Communication Services", 52.7, 0.13, 1.2],
      ["PINS", "Pinterest, Inc.", "Communication Services", 38.9, 0.18, 1.6],
      ["SNAP", "Snap Inc.", "Communication Services", 12.6, 0.26, 2.3],
      ["TME", "Tencent Music (ADR)", "Communication Services", 14.2, 0.16, 1.5],
      ["WMG", "Warner Music Group", "Communication Services", 31.8, 0.1, 1.1],
      ["LYV", "Live Nation Entertainment", "Entertainment", 128.4, 0.14, 1.4],
      ["CMCSA", "Comcast Corporation", "Communication Services", 42.6, 0.07, 0.8],
    ],
  },
  // ------------------------------------------------------------- US consumer
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NYSE (simulated)",
    rows: [
      ["AMZN", "Amazon.com, Inc.", "Consumer Discretionary", 186.9, 0.11, 1.15],
      ["TSLA", "Tesla, Inc.", "Consumer Discretionary", 246.8, 0.2, 1.7],
      ["HD", "The Home Depot, Inc.", "Consumer Discretionary", 401.2, 0.08],
      ["TGT", "Target Corporation", "Consumer Discretionary", 138.6, 0.09, 0.9],
      ["LOW", "Lowe's Companies, Inc.", "Consumer Discretionary", 248.3, 0.08, 0.85],
      ["BKNG", "Booking Holdings Inc.", "Travel & Leisure", 4680.0, 0.11, 1.1],
      ["MAR", "Marriott International", "Travel & Leisure", 242.8, 0.1, 1.1],
      ["DAL", "Delta Air Lines, Inc.", "Airlines", 58.4, 0.16, 1.7],
      ["CCL", "Carnival Corporation", "Travel & Leisure", 24.6, 0.18, 1.9],
      ["EBAY", "eBay Inc.", "Consumer Discretionary", 58.2, 0.09, 1],
      ["DHI", "D.R. Horton, Inc.", "Homebuilders", 158.4, 0.12, 1.4],
      ["LEVI", "Levi Strauss & Co.", "Consumer Discretionary", 18.9, 0.12, 1.3],
      ["NKE", "NIKE, Inc.", "Consumer Discretionary", 76.4, 0.11],
      ["SBUX", "Starbucks Corporation", "Consumer Discretionary", 97.3, 0.09],
      ["LULU", "Lululemon Athletica", "Consumer Discretionary", 318.9, 0.15, 1.4],
      ["F", "Ford Motor Company", "Consumer Discretionary", 11.2, 0.12, 1.3],
      ["GM", "General Motors Company", "Consumer Discretionary", 46.9, 0.13, 1.3],
      ["KO", "The Coca-Cola Company", "Consumer Staples", 63.4, 0.05, 0.6],
      ["PEP", "PepsiCo, Inc.", "Consumer Staples", 168.2, 0.05, 0.6],
      ["WMT", "Walmart Inc.", "Consumer Staples", 71.9, 0.06, 0.65],
      ["COST", "Costco Wholesale Corp.", "Consumer Staples", 881.4, 0.07, 0.7],
      ["PG", "Procter & Gamble Co.", "Consumer Staples", 169.3, 0.05, 0.55],
      ["CL", "Colgate-Palmolive Co.", "Consumer Staples", 96.1, 0.05, 0.55],
      ["MCD", "McDonald's Corporation", "Consumer Staples", 268.5, 0.07, 0.7],
      ["GIS", "General Mills, Inc.", "Consumer Staples", 68.9, 0.05, 0.6],
      ["KHC", "The Kraft Heinz Company", "Consumer Staples", 34.8, 0.06, 0.7],
      ["MDLZ", "Mondelez International", "Consumer Staples", 68.2, 0.06, 0.65],
      ["STZ", "Constellation Brands, Inc.", "Consumer Staples", 242.6, 0.08, 0.85],
      ["TAP", "Molson Coors Beverage", "Consumer Staples", 58.4, 0.07, 0.75],
    ],
  },
  // --------------------------------------------------------------- US health
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NYSE (simulated)",
    rows: [
      ["JNJ", "Johnson & Johnson", "Healthcare", 155.7, 0.05, 0.7],
      ["UNH", "UnitedHealth Group Inc.", "Healthcare", 512.3, 0.09],
      ["LLY", "Eli Lilly and Company", "Healthcare", 812.4, 0.14, 1.3],
      ["PFE", "Pfizer Inc.", "Healthcare", 28.9, 0.07, 0.8],
      ["MRK", "Merck & Co., Inc.", "Healthcare", 108.2, 0.06, 0.8],
      ["ABBV", "AbbVie Inc.", "Healthcare", 198.4, 0.08, 0.9],
      ["MRNA", "Moderna, Inc.", "Biotech", 42.6, 0.24, 2.2],
      ["GILD", "Gilead Sciences, Inc.", "Biotech", 91.3, 0.08, 1],
      ["CRSP", "CRISPR Therapeutics", "Biotech", 54.8, 0.28, 2.5],
      ["CVS", "CVS Health Corporation", "Healthcare", 58.7, 0.1, 1.1],
    ],
  },
  // -------------------------------------------------------------- US finance
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NYSE (simulated)",
    rows: [
      ["JPM", "JPMorgan Chase & Co.", "Financials", 238.7, 0.07, 0.9],
      ["BAC", "Bank of America Corp.", "Financials", 42.8, 0.08, 1],
      ["WFC", "Wells Fargo & Company", "Financials", 58.4, 0.08, 1],
      ["C", "Citigroup Inc.", "Financials", 68.9, 0.09, 1.1],
      ["MS", "Morgan Stanley", "Financials", 118.6, 0.09, 1.1],
      ["SCHW", "The Charles Schwab Corporation", "Financials", 78.2, 0.08, 1],
      ["AXP", "American Express Company", "Financials", 268.4, 0.08, 0.9],
      ["BLK", "BlackRock, Inc.", "Financials", 968.4, 0.08, 0.9],
      ["COF", "Capital One Financial Corp.", "Financials", 148.9, 0.11, 1.2],
      ["PGR", "The Progressive Corporation", "Insurance", 238.6, 0.07, 0.8],
      ["TRV", "The Travelers Companies, Inc.", "Insurance", 248.9, 0.07, 0.85],
      ["AIG", "American International Group", "Insurance", 74.8, 0.08, 1],
      ["MET", "MetLife, Inc.", "Insurance", 78.6, 0.08, 0.95],
      ["ALL", "The Allstate Corporation", "Insurance", 182.4, 0.07, 0.85],
      ["UNM", "Unum Group", "Insurance", 68.4, 0.09, 1],
      ["GS", "The Goldman Sachs Group", "Financials", 512.9, 0.09, 1.1],
      ["V", "Visa Inc.", "Financials", 291.4, 0.07, 0.8],
      ["MA", "Mastercard Incorporated", "Financials", 478.6, 0.07, 0.8],
      ["BRK.B", "Berkshire Hathaway Inc.", "Financials", 452.3, 0.05, 0.6],
      ["HOOD", "Robinhood Markets, Inc.", "Financials", 24.8, 0.25, 2.4],
    ],
  },
  // ------------------------------------------------------- US energy & mining
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NYSE (simulated)",
    rows: [
      ["XOM", "Exxon Mobil Corporation", "Energy", 118.4, 0.13, 1.4],
      ["CVX", "Chevron Corporation", "Energy", 156.7, 0.12, 1.3],
      ["COP", "ConocoPhillips", "Energy", 112.3, 0.15, 1.5],
      ["FCX", "Freeport-McMoRan Inc.", "Materials", 44.6, 0.16, 1.6],
      ["NEM", "Newmont Corporation", "Materials", 51.2, 0.15, 1.5],
      ["BA", "The Boeing Company", "Industrials", 178.4, 0.13, 1.4],
      ["CAT", "Caterpillar Inc.", "Industrials", 372.6, 0.09, 1],
      ["GE", "GE Aerospace", "Industrials", 189.3, 0.1, 1.05],
      ["UPS", "United Parcel Service", "Industrials", 132.7, 0.09, 0.95],
      ["FDX", "FedEx Corporation", "Industrials", 268.4, 0.11, 1.1],
      ["UNP", "Union Pacific Corporation", "Industrials", 238.6, 0.08, 0.85],
      ["CSX", "CSX Corporation", "Industrials", 34.8, 0.08, 0.9],
      ["NSC", "Norfolk Southern Corporation", "Industrials", 248.9, 0.08, 0.9],
      ["MMM", "3M Company", "Industrials", 128.4, 0.07, 0.9],
      ["HON", "Honeywell International Inc.", "Industrials", 218.6, 0.07, 0.85],
      ["LMT", "Lockheed Martin Corporation", "Aerospace & Defense", 486.2, 0.08, 0.8],
      ["NOC", "Northrop Grumman Corporation", "Aerospace & Defense", 482.6, 0.08, 0.85],
      ["GD", "General Dynamics Corporation", "Aerospace & Defense", 288.4, 0.08, 0.85],
      ["TDG", "TransDigm Group Incorporated", "Aerospace & Defense", 1248.0, 0.12, 1],
      ["WM", "Waste Management, Inc.", "Industrials", 218.7, 0.06, 0.7],
      ["PWR", "Quanta Services, Inc.", "Construction & Engineering", 312.8, 0.1, 1],
      ["URI", "United Rentals, Inc.", "Construction & Engineering", 768.4, 0.13, 1.2],
      ["CMI", "Cummins Inc.", "Machinery", 368.9, 0.09, 1],
      ["EMR", "Emerson Electric Co.", "Electrical Equipment", 118.6, 0.07, 0.85],
      ["ROK", "Rockwell Automation, Inc.", "Machinery", 268.4, 0.09, 1],
      ["ITW", "Illinois Tool Works Inc.", "Machinery", 248.6, 0.07, 0.8],
      ["PH", "Parker-Hannifin Corporation", "Machinery", 618.4, 0.09, 0.9],
      ["UAL", "United Airlines Holdings", "Airlines", 98.6, 0.18, 1.9],
      ["AAL", "American Airlines Group Inc.", "Airlines", 18.4, 0.24, 2.2],
      ["LUV", "Southwest Airlines Co.", "Airlines", 32.8, 0.18, 1.8],
      ["AC", "Air Canada", "Airlines", 24.6, 0.2, 1.9],
      ["RTX", "RTX Corporation", "Industrials", 121.4, 0.07, 0.9],
      ["DE", "Deere & Company", "Industrials", 398.5, 0.09, 1],
      ["NEE", "NextEra Energy, Inc.", "Utilities", 78.4, 0.05, 0.5],
      ["DUK", "Duke Energy Corporation", "Utilities", 112.6, 0.04, 0.45],
      ["SO", "The Southern Company", "Utilities", 86.2, 0.04, 0.45],
    ],
  },
  // --------------------------------------------------------- US meme & REITs
  {
    market: "US",
    assetClass: "STOCK",
    exchange: "NASDAQ (simulated)",
    rows: [
      ["GME", "GameStop Corp.", "Meme", 22.4, 0.3, 2.6],
      ["AMC", "AMC Entertainment Holdings", "Meme", 4.8, 0.35, 3],
      ["BBBY", "Bed Bath & Beyond (reborn)", "Meme", 6.2, 0.4, 3.2],
      ["NOK", "Nokia Corporation (ADR)", "Communication Equipment", 4.9, 0.16, 1.8],
      ["ERIC", "Ericsson (ADR)", "Telecom Equipment", 8.4, 0.15, 1.7],
      ["NOKA", "Nokia of AadiBay (fictional)", "Meme", 2.4, 0.3, 2.4],
      ["O", "Realty Income Corporation", "Real Estate", 57.8, 0.06, 0.65],
      ["SPG", "Simon Property Group", "Real Estate", 152.3, 0.08, 0.9],
      ["PLD", "Prologis, Inc.", "Real Estate", 118.6, 0.08, 0.85],
      ["AMT", "American Tower Corporation", "REITs", 218.4, 0.08, 0.85],
      ["EQIX", "Equinix, Inc.", "REITs", 818.6, 0.09, 0.9],
      ["DLR", "Digital Realty Trust, Inc.", "REITs", 158.7, 0.1, 0.95],
      ["AVB", "AvalonBay Communities, Inc.", "REITs", 228.4, 0.07, 0.8],
      ["EQR", "Equity Residential", "REITs", 68.9, 0.06, 0.75],
      ["VICI", "VICI Properties Inc.", "REITs", 31.8, 0.08, 0.85],
      ["WELL", "Welltower Inc.", "REITs", 128.6, 0.08, 0.85],
      ["OKE", "ONEOK, Inc.", "Midstream", 78.4, 0.1, 1],
      ["WMB", "Williams Companies, Inc.", "Midstream", 48.6, 0.1, 1],
      ["KMI", "Kinder Morgan, Inc.", "Midstream", 18.4, 0.09, 0.95],
      ["ET", "Energy Transfer LP", "Midstream", 14.8, 0.12, 1.1],
    ],
  },
  // ------------------------------------------------------------ Canada (TSX)
  {
    market: "CA",
    assetClass: "STOCK",
    exchange: "TSX (simulated)",
    rows: [
      ["RY.TO", "Royal Bank of Canada", "Financials", 168.2, 0.07, 0.85],
      ["TD.TO", "The Toronto-Dominion Bank", "Financials", 78.4, 0.08, 0.9],
      ["BNS.TO", "The Bank of Nova Scotia", "Financials", 66.9, 0.06, 0.85],
      ["BMO.TO", "Bank of Montreal", "Financials", 132.4, 0.07, 0.9],
      ["MFC.TO", "Manulife Financial Corp.", "Financials", 42.3, 0.09, 1.05],
      ["SU.TO", "Suncor Energy Inc.", "Energy", 54.7, 0.14, 1.4],
      ["CNQ.TO", "Canadian Natural Resources", "Energy", 46.2, 0.13, 1.3],
      ["ENB.TO", "Enbridge Inc.", "Energy", 58.9, 0.05, 0.6],
      ["TRP.TO", "TC Energy Corporation", "Energy", 62.4, 0.06, 0.65],
      ["SHOP.TO", "Shopify Inc.", "Technology", 118.7, 0.19, 1.7],
      ["CSU.TO", "Constellation Software Inc.", "Technology", 4180.0, 0.08, 0.9],
      ["TRI.TO", "Thomson Reuters Corporation", "Technology", 228.4, 0.07, 0.8],
      ["OTEX.TO", "Open Text Corporation", "Technology", 42.6, 0.12, 1.2],
      ["ABX.TO", "Barrick Gold Corporation", "Materials", 27.4, 0.15, 1.5],
      ["WPM.TO", "Wheaton Precious Metals", "Materials", 78.2, 0.14, 1.4],
      ["NTR.TO", "Nutrien Ltd.", "Materials", 58.9, 0.13, 1.4],
      ["TECK.B.TO", "Teck Resources Limited", "Materials", 62.3, 0.16, 1.6],
      ["CCO.TO", "Cameco Corporation", "Materials", 68.4, 0.2, 1.9],
      ["FM.TO", "First Quantum Minerals", "Materials", 19.8, 0.25, 2.3],
      ["T.TO", "TELUS Corporation", "Telecom", 21.8, 0.06, 0.6],
      ["BCE.TO", "BCE Inc.", "Telecom", 33.4, 0.06, 0.6],
      ["RCI.B.TO", "Rogers Communications Inc.", "Telecom", 52.6, 0.07, 0.7],
      ["FTS.TO", "Fortis Inc.", "Utilities", 62.8, 0.04, 0.45],
      ["EMA.TO", "Emera Incorporated", "Utilities", 52.3, 0.05, 0.5],
      ["CNR.TO", "Canadian National Railway", "Industrials", 108.4, 0.07, 0.8],
      ["TRIX.TO", "Trix Transport Group", "Industrials", 36.9, 0.11, 1.2],
      ["WCN.TO", "Waste Connections Inc.", "Industrials", 248.6, 0.06, 0.7],
      ["ATD.TO", "Alimentation Couche-Tard", "Consumer Staples", 74.6, 0.06, 0.65],
      ["L.TO", "Loblaw Companies Limited", "Consumer Staples", 178.3, 0.05, 0.6],
      ["QSR.TO", "Restaurant Brands Intl.", "Consumer Discretionary", 98.4, 0.07, 0.8],
      ["REI-UN.TO", "RioCan Real Estate Trust", "Real Estate", 19.6, 0.08, 0.9],
      ["CAR-UN.TO", "CAPREIT Apartments", "Real Estate", 48.9, 0.07, 0.8],
    ],
  },
  // ----------------------------------------------------------- Funds & ETFs
  {
    market: "US",
    assetClass: "ETF",
    exchange: "US ETF Market (simulated)",
    rows: [
      ["SPY", "S&P 500 Index ETF", "Broad Market", 612.4, 0.06, 0.6],
      ["QQQ", "Nasdaq 100 Index ETF", "Broad Market", 528.9, 0.09, 0.85],
      ["VTI", "Total US Market ETF", "Broad Market", 302.6, 0.07, 0.65],
      ["XLK", "Technology Sector ETF", "Sector Fund", 238.4, 0.1, 1],
      ["XLE", "Energy Sector ETF", "Sector Fund", 96.8, 0.12, 1.3],
      ["XLF", "Financial Sector ETF", "Sector Fund", 48.6, 0.07, 0.7],
      ["XLV", "Healthcare Sector ETF", "Sector Fund", 148.2, 0.06, 0.7],
      ["SCHD", "Dividend Champions ETF", "Dividend Fund", 28.9, 0.05, 0.5],
      ["VNQ", "Real Estate Income ETF", "Real Estate", 92.4, 0.07, 0.75],
      ["GLD", "Gold Bullion ETF", "Precious Metals", 268.4, 0.08, 0.9],
      ["IBIT", "Bitcoin Trust ETF", "Crypto Fund", 42.8, 0.25, 2],
      ["TLT", "20+ Year Treasury ETF", "Government Bonds", 94.2, 0.05, 0.4],
      ["SMH", "Semiconductor ETF", "Sector Fund", 268.4, 0.14, 1.4],
      ["IYW", "iShares U.S. Tech ETF", "Sector Fund", 98.6, 0.1, 1],
      ["IYT", "Transportation ETF", "Sector Fund", 68.4, 0.09, 0.95],
      ["ITB", "Home Construction ETF", "Sector Fund", 68.9, 0.11, 1.1],
      ["XBI", "Biotech ETF", "Sector Fund", 88.6, 0.16, 1.6],
      ["ITA", "Aerospace & Defense ETF", "Sector Fund", 148.6, 0.09, 0.85],
      ["JETS", "U.S. Airlines ETF", "Sector Fund", 28.4, 0.16, 1.5],
      ["ARKK", "ARK Innovation ETF", "Disruptive Growth", 58.4, 0.24, 2.2],
      ["QQXS", "Nasdaq Inverse ETF (bearish)", "Inverse Fund", 18.6, 0.16, 1.8],
      ["SLV", "Silver Bullion ETF", "Precious Metals", 28.4, 0.1, 1.5],
      ["UNG", "Natural Gas Fund", "Commodity Fund", 14.8, 0.2, 2.4],
      ["USO", "Crude Oil Fund", "Commodity Fund", 68.4, 0.14, 1.9],
      ["PDBC", "Broad Commodity ETF", "Commodity Fund", 18.4, 0.1, 1.3],
      ["EEM", "Emerging Markets ETF", "International Equity", 48.6, 0.11, 1.1],
      ["FXI", "China Large-Cap ETF", "International Equity", 28.4, 0.13, 1.3],
      ["EWJ", "Japan Equity ETF", "International Equity", 68.9, 0.08, 0.9],
      ["VGK", "Europe Equity ETF", "International Equity", 58.4, 0.08, 0.9],
      ["XLU", "Utilities Sector ETF", "Sector Fund", 78.4, 0.05, 0.55],
      ["REZ", "Residential REIT ETF", "Real Estate", 38.6, 0.07, 0.8],
      ["AGG", "US Aggregate Bond ETF", "Government Bonds", 98.6, 0.03, 0.25],
      ["SHV", "Short-Term Treasury ETF", "Cash-Like", 108.4, 0.01, 0.05],
      ["BIL", "T-Bill ETF (cash proxy)", "Cash-Like", 91.6, 0.01, 0.04],
    ],
  },
  {
    market: "CA",
    assetClass: "ETF",
    exchange: "TSX (simulated)",
    rows: [
      ["CP.TO", "Canadian Pacific Kansas City", "Industrials", 98.4, 0.08, 0.85],
      ["DOL.TO", "Dollarama Inc.", "Consumer Discretionary", 128.6, 0.1, 0.9],
      ["GIL.TO", "Gildan Activewear Inc.", "Consumer Discretionary", 48.6, 0.1, 1],
      ["CJR.B.TO", "Corus Entertainment", "Media", 4.8, 0.14, 1.5],
      ["BDT.TO", "Black Diamond Group", "Industrials", 8.4, 0.14, 1.4],
      ["XIC.TO", "iShares Core S&P/TSX ETF", "Broad Market", 38.6, 0.06, 0.6],
      ["XEQT.TO", "All-Equity Portfolio ETF", "Broad Market", 32.4, 0.07, 0.65],
      ["VFV.TO", "S&P 500 Index ETF (CAD)", "Broad Market", 148.7, 0.07, 0.65],
      ["HXT.TO", "S&P/TSX 60 Index ETF", "Broad Market", 52.8, 0.06, 0.6],
      ["ZDV.TO", "Canadian Dividend ETF", "Dividend Fund", 21.6, 0.05, 0.5],
      ["XBB.TO", "Canadian Bond Universe ETF", "Government Bonds", 29.4, 0.03, 0.3],
      ["ZAG.TO", "Aggregate Bond Index ETF", "Government Bonds", 15.2, 0.03, 0.28],
      ["XEG.TO", "Canadian Energy ETF", "Sector Fund", 18.9, 0.12, 1.3],
    ],
  },
  // ----------------------------------------------------------------- Crypto
  {
    market: "US",
    assetClass: "CRYPTO",
    exchange: "Crypto Market (simulated, 24/7)",
    rows: [
      ["BTC", "Bitcoin (simulated)", "Crypto", 92400.0, 0.1, 2.6],
      ["ETH", "Ethereum (simulated)", "Crypto", 3180.0, 0.12, 2.8],
      ["SOL", "Solana (simulated)", "Crypto", 186.4, 0.16, 3.2],
      ["XRP", "XRP (simulated)", "Crypto", 0.92, 0.18, 3.2],
      ["ADA", "Cardano (simulated)", "Crypto", 0.72, 0.17, 3.1],
      ["AVAX", "Avalanche (simulated)", "Crypto", 38.6, 0.2, 3.3],
      ["LINK", "Chainlink (simulated)", "Crypto", 18.4, 0.19, 3.2],
      ["DOT", "Polkadot (simulated)", "Crypto", 6.8, 0.2, 3.3],
      ["MATIC", "Polygon (simulated)", "Crypto", 0.48, 0.22, 3.4],
      ["ATOM", "Cosmos (simulated)", "Crypto", 8.4, 0.2, 3.3],
      ["LTC", "Litecoin (simulated)", "Crypto", 88.6, 0.14, 2.8],
      ["BCH", "Bitcoin Cash (simulated)", "Crypto", 428.6, 0.16, 3],
      ["UNI", "Uniswap (simulated)", "Crypto", 12.8, 0.24, 3.5],
      ["AAVE", "Aave (simulated)", "Crypto", 248.6, 0.22, 3.4],
      ["SHIB", "Shiba Inu (simulated)", "Meme Crypto", 0.0000248, 0.28, 3.8],
      ["PEPE", "Pepe (simulated)", "Meme Crypto", 0.0000118, 0.32, 4],
      ["DOGE", "Dogecoin (simulated)", "Meme Crypto", 0.18, 0.25, 3.6],
      ["FARTCOIN", "Fartcoin (simulated)", "Meme Crypto", 0.86, 0.34, 4.2],
    ],
  },
  // ------------------------------------------------------------ Commodities
  {
    market: "US",
    assetClass: "COMMODITY",
    exchange: "Commodities Desk (simulated)",
    rows: [
      ["GOLD", "Gold (per ounce)", "Precious Metals", 2680.0, 0.06, 1.2],
      ["SILVER", "Silver (per ounce)", "Precious Metals", 32.4, 0.1, 1.9],
      ["OIL", "Crude Oil WTI (per barrel)", "Energy", 71.2, 0.14, 2.3],
      ["NATGAS", "Natural Gas (per MMBtu)", "Energy", 2.68, 0.2, 3],
      ["COPPER", "Copper (per pound)", "Metals", 4.28, 0.11, 1.8],
      ["URANIUM", "Uranium (per pound)", "Energy", 78.4, 0.16, 2.2],
      ["WHEAT", "Wheat (per bushel)", "Agriculture", 5.64, 0.12, 1.9],
      ["CORN", "Corn (per bushel)", "Agriculture", 4.28, 0.1, 1.7],
      ["SOYBEAN", "Soybeans (per bushel)", "Agriculture", 12.6, 0.09, 1.6],
      ["COFFEE", "Coffee (per pound)", "Softs", 2.48, 0.16, 2.3],
      ["COCOA", "Cocoa (per tonne)", "Softs", 6840.0, 0.2, 2.6],
      ["SUGAR", "Sugar (per pound)", "Softs", 0.21, 0.14, 2],
      ["COTTON", "Cotton (per pound)", "Softs", 0.72, 0.13, 1.9],
      ["ORANGE", "Orange Juice (per pound)", "Softs", 4.18, 0.18, 2.4],
      ["PLATINUM", "Platinum (per ounce)", "Precious Metals", 968.4, 0.11, 1.7],
      ["PALLADIUM", "Palladium (per ounce)", "Precious Metals", 1028.0, 0.14, 2],
      ["LITHIUM", "Lithium Carbonate (per tonne)", "Battery Metals", 14800.0, 0.18, 2.4],
      ["COBALT", "Cobalt (per pound)", "Battery Metals", 14.2, 0.17, 2.3],
      ["NICKEL", "Nickel (per pound)", "Battery Metals", 8.6, 0.15, 2.1],
      ["ALUMINUM", "Aluminum (per pound)", "Metals", 1.18, 0.1, 1.6],
      ["STEEL", "Steel Rebar (per tonne)", "Metals", 682.0, 0.1, 1.6],
      ["HEATOIL", "Heating Oil (per gallon)", "Energy", 2.24, 0.13, 2],
      ["GASOLINE", "RBOB Gasoline (per gallon)", "Energy", 2.08, 0.14, 2.1],
      ["ETHANOL", "Ethanol (per gallon)", "Energy", 1.68, 0.12, 1.8],
      ["CATTLE", "Live Cattle (per pound)", "Livestock", 1.86, 0.07, 1.2],
      ["HOGS", "Lean Hogs (per pound)", "Livestock", 0.88, 0.11, 1.6],
      ["LUMBER", "Lumber (per 1000 board ft)", "Agriculture", 512.0, 0.15, 2.1],
    ],
  },
  // ---------------------------------------------------------------- Bonds
  {
    market: "US",
    assetClass: "BOND",
    exchange: "Bond Desk (simulated)",
    rows: [
      ["CAN10Y", "Canada 10-Year Bond", "Government Bonds", 98.4, 0.03, 0.35],
      ["US10Y", "US 10-Year Treasury", "Government Bonds", 96.8, 0.03, 0.35],
      ["CORP", "Investment Grade Corp Bond", "Corporate Bonds", 92.4, 0.04, 0.45],
      ["HYBOND", "High Yield Bond", "Corporate Bonds", 88.6, 0.08, 0.6],
      ["MUNI", "Municipal Bond Fund", "Municipal Bonds", 94.8, 0.02, 0.25],
      ["TIPS", "Inflation-Protected Bond", "Government Bonds", 102.6, 0.03, 0.3],
      ["JUNK-3M", "Junk Bond ETF (short)", "Corporate Bonds", 42.8, 0.06, 0.55],
      ["EMB", "Emerging Market Bond", "Government Bonds", 88.4, 0.06, 0.6],
      ["GIC-1Y", "1-Year GIC (4.00%)", "Cash-Like", 100.0, 0.01, 0.05],
      ["GIC-5Y", "5-Year GIC (3.75%)", "Cash-Like", 100.0, 0.015, 0.08],
      ["HISA", "High-Interest Savings ETF", "Cash-Like", 50.0, 0.005, 0.02],
      ["CASH.TO", "Canadian Money Market ETF", "Cash-Like", 50.0, 0.005, 0.02],
    ],
  },
  // -------------------------------------------------------- AadiVerse (fiction)
  {
    market: "AADI",
    assetClass: "STOCK",
    exchange: "AadiVerse Exchange (fictional)",
    rows: [
      ["AADIDEV", HOUSE_STOCK_NAME, "AadiVerse", 20.0, 0.18, 1.6],
      ["MAYHEM", "Market Mayhem Studios", "AadiVerse", 34.5, 0.22, 2.2],
      ["MOON", "Moonbase Energy", "AadiVerse", 64.2, 0.2, 2],
      ["HODL", "Hodl Industries", "AadiVerse", 46.8, 0.16, 1.8],
      ["YOLO", "Yolo Robotics", "Meme", 12.4, 0.28, 2.6],
      ["FOMO", "Fomo Labs", "Meme", 8.6, 0.3, 2.8],
      ["PAPER", "Paper Hands Inc.", "Meme", 3.2, 0.26, 2.4],
      ["DIAMOND", "Diamond Hands Corp.", "Meme", 27.9, 0.24, 2.2],
      ["BAGHOLDER", "Bagholders Anonymous", "Meme", 1.8, 0.34, 3],
      ["TOTMOON", "To The Moon Logistics", "AadiVerse", 18.6, 0.24, 2.3],
      ["WAGMI", "WAGMI Games", "Gaming", 6.8, 0.28, 2.8],
      ["NGMI", "NGMI Biotech", "Biotech", 4.2, 0.32, 3.2],
      ["APEX", "Apex Aadi Holdings", "AadiVerse", 84.6, 0.16, 1.6],
      ["STONKS", "Stonks Only Go Up Corp.", "Meme", 9.4, 0.3, 2.9],
      ["GIGACHAD", "Gigachad Energy drinks", "Beverages", 16.8, 0.2, 2.2],
      ["ZOOMER", "Zoomer Media Group", "Media", 11.2, 0.18, 2],
      ["BOOMER", "Boomer Retirement Corp.", "Financials", 42.8, 0.08, 0.9],
      ["MILK", "Big Milk Conglomerate", "Consumer Staples", 28.4, 0.06, 0.8],
      ["COPING", "Coping Mechanisms Inc.", "Healthcare", 7.6, 0.2, 2.4],
    ],
  },
];

/** Hand-written blurbs for the listings players are most likely to click. */
const DESCRIPTION_OVERRIDES: Record<string, string> = {
  AAPL: "Simulated listing: a large consumer-technology company known for smartphones, computers and digital services. In this simulation a single product launch can move it a lot.",
  AADIDEV:
    "The house listing of the AadiVerse: a scrappy fictional software company. Every new player is gifted one share, and it is famous for wild swings on fake rumours.",
  MAYHEM:
    "A fictional game studio that ships chaos for a living. Its price reacts to hype, delays and the occasional catastrophic bug.",
  GME: "Simulated listing: the original meme stock. Fundamentals are thin, crowd psychology is not.",
  AMC: "Simulated listing: a cinema chain that trades on vibes as much as earnings.",
  BTC: "Simulated crypto asset. Expect violent swings and 24/7 moves — perfect for practising position sizing.",
  GOLD: "Simulated gold price. Historically the classic 'hide from the storm' asset in this game's scenario engine.",
  CAN10Y: "Simulated Government of Canada 10-year bond. Tiny moves, steady — the boring-but-safe end of the market.",
  SPY: "Simulated S&P 500 index fund: one purchase, 500 companies' worth of diversification.",
  US10Y: "Simulated US Treasury. When crashes hit, money tends to hide here.",
  XEQT: "A simulated all-equity ETF — the classic 'just buy everything' starter position.",
};

function describe(
  name: string,
  sector: string,
  assetClass: AssetClass,
): string {
  switch (assetClass) {
    case "ETF":
      return `${name} — a simulated fund that holds a basket of ${sector.toLowerCase()} securities. One purchase, instant diversification.`;
    case "CRYPTO":
      return `${name} — a simulated crypto asset in the AadiVerse. Prices here are fictional and extremely volatile.`;
    case "COMMODITY":
      return `${name} — a simulated commodity price series. Commodities trade on supply, weather and geopolitics in this game.`;
    case "BOND":
      return `${name} — a simulated fixed-income instrument. Small moves, steady drift: the calm corner of the market.`;
    default:
      return `${name} — a simulated ${sector.toLowerCase()} company. Every price, headline and fundamental here is fictional education material.`;
  }
}

function buildSections(): StockDef[] {
  const out: StockDef[] = [];
  let seed = 11;
  for (const section of SECTIONS) {
    for (const [symbol, name, sector, basePrice, drift, vol] of section.rows) {
      seed += 6;
      out.push({
        symbol,
        name,
        exchange: section.exchange,
        market: section.market,
        assetClass: section.assetClass,
        sector,
        description:
          DESCRIPTION_OVERRIDES[symbol] ?? describe(name, sector, section.assetClass),
        basePrice,
        drift,
        vol: vol ?? VOL_BY_CLASS[section.assetClass],
        seed,
      });
    }
  }
  return out;
}

export const STOCKS: StockDef[] = buildSections();

const bySymbol = new Map(STOCKS.map((s) => [s.symbol, s]));

/**
 * Symbols that used to exist and may still sit in portfolios, orders or the
 * ledger (the tutorial stock was renamed when the app became Market Mayhem).
 * They resolve to their replacement so old holdings keep working.
 */
const LEGACY_SYMBOLS: Record<string, string> = {
  "AADI-DEMO": "AADIDEV",
};

export function canonicalSymbol(symbol: string): string {
  const upper = symbol.toUpperCase();
  return LEGACY_SYMBOLS[upper] ?? upper;
}

export function getStockDef(symbol: string): StockDef | undefined {
  return bySymbol.get(canonicalSymbol(symbol));
}

export function listStockDefs(): StockDef[] {
  return STOCKS;
}

/** Every sector present in the universe, in catalogue order. */
export function listSectors(): string[] {
  const seen: string[] = [];
  for (const s of STOCKS) if (!seen.includes(s.sector)) seen.push(s.sector);
  return seen;
}
